// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core.Deta;

namespace Shop2.Migrations
{
    [DbContext(typeof(Shop2DB))]
    [Migration("20240709045952_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domon1.ENtityes.Gropkala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name_grop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Gropkala");
                });

            modelBuilder.Entity("Domon1.ENtityes.kala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ghimat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("grop_Kala1id")
                        .HasColumnType("int");

                    b.Property<string>("mojodi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("grop_Kala1id");

                    b.ToTable("kala");
                });

            modelBuilder.Entity("Domon1.ENtityes.kala", b =>
                {
                    b.HasOne("Domon1.ENtityes.Gropkala", "grop_Kala1")
                        .WithMany("kala1")
                        .HasForeignKey("grop_Kala1id");

                    b.Navigation("grop_Kala1");
                });

            modelBuilder.Entity("Domon1.ENtityes.Gropkala", b =>
                {
                    b.Navigation("kala1");
                });
#pragma warning restore 612, 618
        }
    }
}
